version: "3.9"
services:
  postgres:
    image: postgres
    container_name: pg
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: deliverynow
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network

  app:
    build: .
    container_name: delivery-api
    depends_on:
      - postgres
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    networks:
      - app_network
volumes:
  pgdata:
    driver: local
networks:
  app_network:
    driver: bridge